name: CI

on:
  push:
  pull_request:

jobs:
  test:
    name: Lint, Type Check, Test, Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run linter
        run: pnpm exec turbo lint

      - name: Run type check
        run: pnpm exec turbo check-types

      - name: Build packages
        run: pnpm exec turbo build

      - name: Install Playwright
        run: npx playwright install chromium --with-deps

      - name: Run tests
        run: pnpm exec turbo test

      - name: Upload test results on failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: e2e-test-results
          path: |
            playwright-report/
            test-results/
