name: Release Packages

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed
    branches:
      - main

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "pnpm"
          registry-url: 'https://registry.npmjs.org'
      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm exec turbo build

      - name: Run tests
        run: pnpm exec turbo test

      - name: Create Release Pull Request or Update Versions
        id: changesets
        uses: changesets/action@v1
        with:
          version: pnpm changeset:version
          commit: "chore: release packages"
          title: "chore: release packages"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Prepare packages for release (clean dependencies)
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo "🧹 Cleaning dependencies for release..."
          pnpm prepare-release
          echo "✅ Dependencies cleaned successfully"

      - name: Publish to NPM Registry (with dependency order)
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo "📦 Publishing to NPM with Changesets (dependency order guaranteed)..."

          # Configure .npmrc for Changesets to use correct registries
          echo "registry=https://registry.npmjs.org/" >> ~/.npmrc
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc
          echo "@snapkit-studio:registry=https://registry.npmjs.org/" >> ~/.npmrc

          pnpm changeset:publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Setup Node.js for GitHub Package Registry
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
          scope: '@snapkit-studio'

      - name: Publish to GitHub Package Registry (sequential order)
        if: steps.changesets.outputs.hasChangesets == 'false'
        run: |
          echo "📦 Publishing to GitHub Package Registry in dependency order..."

          # Configure npm for GitHub registry
          echo "@snapkit-studio:registry=https://npm.pkg.github.com" >> ~/.npmrc
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }}" >> ~/.npmrc

          # Publish in dependency order: core → react → nextjs
          echo "1️⃣ Publishing core package..."
          cd packages/core
          npm publish --registry=https://npm.pkg.github.com --access=public && echo "✅ Core published" || echo "❌ Core failed"
          cd ../..

          echo "2️⃣ Publishing react package..."
          cd packages/react
          npm publish --registry=https://npm.pkg.github.com --access=public && echo "✅ React published" || echo "❌ React failed"
          cd ../..

          echo "3️⃣ Publishing nextjs package..."
          cd packages/nextjs
          npm publish --registry=https://npm.pkg.github.com --access=public && echo "✅ NextJS published" || echo "❌ NextJS failed"
          cd ../..

          echo "🎉 GitHub Package Registry publishing completed!"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Send Slack notification on success
        if: steps.changesets.outputs.hasChangesets == 'false'
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "channel": "#releases",
              "username": "SnapKit Release Bot",
              "icon_emoji": ":rocket:",
              "attachments": [
                {
                  "color": "good",
                  "title": "🎉 Release Success!",
                  "fields": [
                    {
                      "title": "📦 NPM Registry",
                      "value": "${{ steps.changesets.outputs.publishedPackages }}",
                      "short": false
                    },
                    {
                      "title": "📦 GitHub Package Registry",
                      "value": "Published successfully",
                      "short": true
                    },
                    {
                      "title": "👤 Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    }
                  ],
                  "footer": "SnapKit Release System",
                  "footer_icon": "https://github.com/snapkit-studio.png",
                  "ts": "${{ github.event.head_commit.timestamp }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Send Slack notification on failure
        if: failure()
        uses: slackapi/slack-github-action@v2.1.0
        with:
          webhook-type: incoming-webhook
          payload: |
            {
              "channel": "#releases",
              "username": "SnapKit Release Bot",
              "icon_emoji": ":x:",
              "attachments": [
                {
                  "color": "danger",
                  "title": "❌ Release Failed!",
                  "fields": [
                    {
                      "title": "🚫 Workflow",
                      "value": "${{ github.workflow }}",
                      "short": true
                    },
                    {
                      "title": "👤 Author",
                      "value": "${{ github.actor }}",
                      "short": true
                    },
                    {
                      "title": "🔗 Action Run",
                      "value": "<https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}|View Details>",
                      "short": false
                    },
                    {
                      "title": "🔗 Commit",
                      "value": "<https://github.com/${{ github.repository }}/commit/${{ github.sha }}|${{ github.sha }}>",
                      "short": false
                    }
                  ],
                  "footer": "Please check the workflow logs and fix any issues.",
                  "footer_icon": "https://github.com/snapkit-studio.png",
                  "ts": "${{ github.event.repository.pushed_at }}"
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}