name: Test External Next.js with Canary

on:
  push:
    branches: [main]
    paths:
      - 'packages/**'
      - 'test-fixtures/**'
      - '.github/workflows/test-external-nextjs.yml'
  pull_request:
    branches: [main]
    paths:
      - 'packages/**'
      - 'test-fixtures/**'
      - '.github/workflows/test-external-nextjs.yml'

jobs:
  publish-canary:
    runs-on: ubuntu-latest
    outputs:
      core-version: ${{ steps.publish.outputs.core-version }}
      react-version: ${{ steps.publish.outputs.react-version }}
      nextjs-version: ${{ steps.publish.outputs.nextjs-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build packages
        run: pnpm build

      - name: Prepare packages for release
        run: |
          # First prepare the packages to create package.release.json files
          pnpm prepare-release

      - name: Generate canary versions
        id: versions
        run: |
          # 현재 package.json에서 직접 버전 읽기 (package.release.json 의존성 제거)
          echo "Reading current versions from package.json files..."
          CORE_VERSION=$(node -p "require('./packages/core/package.json').version")
          REACT_VERSION=$(node -p "require('./packages/react/package.json').version")
          NEXTJS_VERSION=$(node -p "require('./packages/nextjs/package.json').version")

          echo "Current versions:"
          echo "- Core: ${CORE_VERSION}"
          echo "- React: ${REACT_VERSION}"
          echo "- NextJS: ${NEXTJS_VERSION}"

          # 고유한 카나리 suffix 생성
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          COMMIT_SHA=${GITHUB_SHA::7}
          CANARY_SUFFIX="canary.${TIMESTAMP}.${COMMIT_SHA}"

          # 카나리 버전 생성 (기존 버전에 카나리 suffix 추가)
          CORE_CANARY="${CORE_VERSION}-${CANARY_SUFFIX}"
          REACT_CANARY="${REACT_VERSION}-${CANARY_SUFFIX}"
          NEXTJS_CANARY="${NEXTJS_VERSION}-${CANARY_SUFFIX}"

          echo "core-version=${CORE_CANARY}" >> $GITHUB_OUTPUT
          echo "react-version=${REACT_CANARY}" >> $GITHUB_OUTPUT
          echo "nextjs-version=${NEXTJS_CANARY}" >> $GITHUB_OUTPUT

          echo "Generated canary versions:"
          echo "- Core: ${CORE_CANARY}"
          echo "- React: ${REACT_CANARY}"
          echo "- NextJS: ${NEXTJS_CANARY}"

      - name: Update package versions for canary release
        run: |
          # Update package.release.json versions
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.versions.outputs.core-version }}\"/" packages/core/package.release.json
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.versions.outputs.react-version }}\"/" packages/react/package.release.json
          sed -i "s/\"version\": \".*\"/\"version\": \"${{ steps.versions.outputs.nextjs-version }}\"/" packages/nextjs/package.release.json

          # Update react dependency in nextjs package
          sed -i "s/\"@snapkit-studio\/react\": \".*\"/\"@snapkit-studio\/react\": \"${{ steps.versions.outputs.react-version }}\"/" packages/nextjs/package.release.json
          # Update core dependencies
          sed -i "s/\"@snapkit-studio\/core\": \".*\"/\"@snapkit-studio\/core\": \"${{ steps.versions.outputs.core-version }}\"/" packages/react/package.release.json
          sed -i "s/\"@snapkit-studio\/core\": \".*\"/\"@snapkit-studio\/core\": \"${{ steps.versions.outputs.core-version }}\"/" packages/nextjs/package.release.json

          # Debug: Show updated versions
          echo "Updated package.release.json versions:"
          echo "Core: $(grep '"version":' packages/core/package.release.json)"
          echo "React: $(grep '"version":' packages/react/package.release.json)"
          echo "NextJS: $(grep '"version":' packages/nextjs/package.release.json)"

      - name: Publish canary versions
        id: publish
        run: |
          # Configure NPM authentication
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

          # Publish in dependency order with canary tag
          echo "Publishing core package..."
          cd packages/core
          cp package.release.json package.json  # Use canary version for publishing
          echo "About to publish $(node -p 'require("./package.json").name + "@" + require("./package.json").version')"
          npm publish --tag canary --access public || {
            echo "Core package publish failed. Checking if already exists..."
            npm view "@snapkit-studio/core@$(node -p 'require("./package.json").version')" version && echo "Version already exists, continuing..." || exit 1
          }
          cd ../..

          echo "Publishing react package..."
          cd packages/react
          cp package.release.json package.json  # Use canary version for publishing
          echo "About to publish $(node -p 'require("./package.json").name + "@" + require("./package.json").version')"
          npm publish --tag canary --access public || {
            echo "React package publish failed. Checking if already exists..."
            npm view "@snapkit-studio/react@$(node -p 'require("./package.json").version')" version && echo "Version already exists, continuing..." || exit 1
          }
          cd ../..

          echo "Publishing nextjs package..."
          cd packages/nextjs
          cp package.release.json package.json  # Use canary version for publishing
          echo "About to publish $(node -p 'require("./package.json").name + "@" + require("./package.json").version')"
          npm publish --tag canary --access public || {
            echo "NextJS package publish failed. Checking if already exists..."
            npm view "@snapkit-studio/nextjs@$(node -p 'require("./package.json").version')" version && echo "Version already exists, continuing..." || exit 1
          }
          cd ../..

          # Set outputs for other jobs
          echo "core-version=${{ steps.versions.outputs.core-version }}" >> $GITHUB_OUTPUT
          echo "react-version=${{ steps.versions.outputs.react-version }}" >> $GITHUB_OUTPUT
          echo "nextjs-version=${{ steps.versions.outputs.nextjs-version }}" >> $GITHUB_OUTPUT
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  test-external-app:
    needs: publish-canary
    runs-on: ubuntu-latest
    env:
      CORE_VERSION: ${{ needs.publish-canary.outputs.core-version }}
      REACT_VERSION: ${{ needs.publish-canary.outputs.react-version }}
      NEXTJS_VERSION: ${{ needs.publish-canary.outputs.nextjs-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup external test app
        run: |
          # Copy test fixture to temp directory
          cp -r test-fixtures/nextjs-external-app /tmp/test-app
          cd /tmp/test-app

          # Replace placeholders in package.json template with canary versions
          sed "s|CORE_TARBALL_PATH|$CORE_VERSION|g" package.json.template > package.json.tmp
          sed "s|REACT_TARBALL_PATH|$REACT_VERSION|g" package.json.tmp > package.json.tmp2
          sed "s|NEXTJS_TARBALL_PATH|$NEXTJS_VERSION|g" package.json.tmp2 > package.json
          rm package.json.tmp package.json.tmp2

          # Install dependencies from NPM registry
          npm install

      - name: Build external test app
        run: |
          cd /tmp/test-app
          npm run build

      - name: Install Playwright browsers
        run: |
          cd /tmp/test-app
          npx playwright install chromium

      - name: Run E2E tests
        run: |
          cd /tmp/test-app
          npx playwright test

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-node22
          path: /tmp/test-app/test-results/
          retention-days: 7

      - name: Upload trace on failure
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: playwright-traces-node22
          path: /tmp/test-app/test-results/
          retention-days: 7

  test-ssr-hydration:
    runs-on: ubuntu-latest
    needs: publish-canary
    env:
      CORE_VERSION: ${{ needs.publish-canary.outputs.core-version }}
      REACT_VERSION: ${{ needs.publish-canary.outputs.react-version }}
      NEXTJS_VERSION: ${{ needs.publish-canary.outputs.nextjs-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup and test SSR
        run: |
          cp -r test-fixtures/nextjs-external-app /tmp/ssr-test
          cd /tmp/ssr-test

          # Setup package.json with canary versions
          sed "s|CORE_TARBALL_PATH|$CORE_VERSION|g" package.json.template > package.json.tmp
          sed "s|REACT_TARBALL_PATH|$REACT_VERSION|g" package.json.tmp > package.json.tmp2
          sed "s|NEXTJS_TARBALL_PATH|$NEXTJS_VERSION|g" package.json.tmp2 > package.json
          rm package.json.tmp package.json.tmp2

          # Install dependencies from NPM registry
          npm install
          npm run build

          # Test production build
          npm run start &
          sleep 10

          # Test SSR output
          curl -s http://localhost:3000/test-server | grep -q "data-testid=\"server-image-basic\""
          if [ $? -eq 0 ]; then
            echo "✅ SSR test passed: ServerImage rendered correctly"
          else
            echo "❌ SSR test failed: ServerImage not found in HTML"
            exit 1
          fi

          # Kill the server
          kill %1

  test-client-hydration:
    runs-on: ubuntu-latest
    needs: publish-canary
    env:
      CORE_VERSION: ${{ needs.publish-canary.outputs.core-version }}
      REACT_VERSION: ${{ needs.publish-canary.outputs.react-version }}
      NEXTJS_VERSION: ${{ needs.publish-canary.outputs.nextjs-version }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare and test hydration
        run: |
          cp -r test-fixtures/nextjs-external-app /tmp/hydration-test
          cd /tmp/hydration-test

          # Setup package.json with canary versions
          sed "s|CORE_TARBALL_PATH|$CORE_VERSION|g" package.json.template > package.json.tmp
          sed "s|REACT_TARBALL_PATH|$REACT_VERSION|g" package.json.tmp > package.json.tmp2
          sed "s|NEXTJS_TARBALL_PATH|$NEXTJS_VERSION|g" package.json.tmp2 > package.json
          rm package.json.tmp package.json.tmp2

          # Install dependencies from NPM registry
          npm install
          npx playwright install chromium

          # Run specific hydration test
          npx playwright test client-interaction.spec.ts --reporter=list

  cleanup-canary:
    runs-on: ubuntu-latest
    needs: [publish-canary, test-external-app, test-ssr-hydration, test-client-hydration]
    if: always()

    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Cleanup canary versions
        run: |
          # Configure NPM authentication
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" >> ~/.npmrc

          # Unpublish canary versions (optional - for cleanup)
          echo "Cleaning up canary versions..."
          # Note: npm unpublish requires wait time after publish, so these might fail
          npm unpublish @snapkit-studio/nextjs@${{ needs.publish-canary.outputs.nextjs-version }} --force 2>/dev/null || echo "NextJS cleanup skipped"
          npm unpublish @snapkit-studio/react@${{ needs.publish-canary.outputs.react-version }} --force 2>/dev/null || echo "React cleanup skipped"
          npm unpublish @snapkit-studio/core@${{ needs.publish-canary.outputs.core-version }} --force 2>/dev/null || echo "Core cleanup skipped"

          echo "Canary cleanup completed"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}